version: '3.8'
services: 
  postgres:
    image: postgres:latest
    volumes: 
      postgres_data:/var/lib/postgres/data
    environment: 
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      mynetwork
  backend:
  
  frontend:

networks:
  mynetwork:

volumes:
  postgres_data: